### ISSUE TITLE
It is not possible to use GPUs or NPUs on Android

### ISSUE THREAD

**Issue by ZTMIDGO** [deep-diver/keras-sd-serving#6]
I am running tflite from sd with android,but model unavailable accelerated using GPUs or NPUs.

**Comment by deep-diver** [comment]
How did you run the models on Android?

**Comment by ZTMIDGO** [comment]
> How did you run the models on Android?

Here https://github.com/ZTMIDGO/Android-Stable-diffusion-ONNX

Unfortunately, the SD model running on the onnxruntime does not support NNAPI, if you succeed in making the SD model of tflite use NNAPI or GPU, I will rewrite a Tensorflow project

**Comment by caofx0418** [comment]
> 

I use your project in Lenovo Phone, it can acclerate by NNAPI, but only some ops
